name: first

on: 
  workflow_dispatch:

jobs: 
  demo: 
    runs-on: ubuntu-latest
    
    steps: 
    
    - uses: actions/checkout@master

    - name: usenode
      uses: actions/setup-node@v2
      with: 
        node-version: 14.x

    - name: sharp
      run: |
        npm install -g sharp-cli